name: QMAP Paper Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8

    - name: Create and activate conda environment
      run: |
        conda create -n qmap_paper python=3.8 -y
        echo "conda activate qmap_paper" >> $GITHUB_ENV

    - name: Install the current repo
      run: |
        cd 2024_qmap_paper
        pip install .

    - name: Download data
      run: wget -O data.zip https://figshare.com/ndownloader/files/44981896

    - name: Unzip data
      run: unzip data.zip

    - name: Install ViennaRNA
      run: conda install -c bioconda viennarna -y

    - name: Generate sets
      run: python qmap_paper/cli.py generate-sets

    - name: Generate scaffold sets
      run: python qmap_paper/cli.py generate-scaffold-sets

    - name: Generate scaffold sets again
      run: python qmap_paper/cli.py generate-scaffold-sets

    - name: Randomize helices
      run: python qmap_paper/cli.py randomize-helices

    - name: Barcode libraries
      run: python qmap_paper/cli.py barcode-libraries

    - name: Clean up and unzip data again
      run: |
        rm -rf data
        unzip data.zip

    - name: Process sequencing data
      run: python qmap_paper/cli.py process-sequencing-data

    - name: Characterize mutations
      run: python qmap_paper/cli.py characterize-mutations
