name: QMAP Paper Workflow

on: [push]

jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # Set default shell to login shell

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge,bioconda,defaults
        auto-activate-base: true
        python-version: 3.8

    - name: Initialize Conda
      run: conda init bash

    - name: Create environment and install dependencies
      run: |
        conda create --name qmap-env -y
        source ~/.bashrc
        conda activate qmap-env
        conda install -c bioconda viennarna -y
        conda install -c conda-forge -c bioconda -c defaults python=3.8 -y
        conda activate qmap-env  # Ensure the environment is active

    - name: Install the current repo
      run: pip install .

    - name: Verify ViennaRNA installation
      run: |
        which RNAfold
        RNAfold --version

    - name: Download data
      run: wget -O data.zip https://figshare.com/ndownloader/files/44981896

    - name: Unzip data
      run: unzip data.zip

    - name: Generate sets
      run: python qmap_paper/cli.py generate-sets

    - name: Generate scaffold sets
      run: python qmap_paper/cli.py generate-scaffold-sets

    - name: Randomize helices
      run: python qmap_paper/cli.py randomize-helices

    - name: Barcode libraries
      run: python qmap_paper/cli.py barcode-libraries

    - name: Clean up and unzip data again
      run: |
        rm -rf data
        unzip data.zip

    - name: Process sequencing data
      run: python qmap_paper/cli.py process-sequencing-data

    - name: Characterize mutations
      run: python qmap_paper/cli.py characterize-mutations